// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/broadcast/listen.ts";
import * as $3 from "./routes/api/broadcast/send.ts";
import * as $4 from "./routes/api/joke.ts";
import * as $5 from "./routes/api/user/[id].ts";
import * as $6 from "./routes/api/user/index.ts";
import * as $7 from "./routes/greet/[name].tsx";
import * as $8 from "./routes/index.tsx";
import * as $$0 from "./islands/Chat.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/KVDemo.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/broadcast/listen.ts": $2,
    "./routes/api/broadcast/send.ts": $3,
    "./routes/api/joke.ts": $4,
    "./routes/api/user/[id].ts": $5,
    "./routes/api/user/index.ts": $6,
    "./routes/greet/[name].tsx": $7,
    "./routes/index.tsx": $8,
  },
  islands: {
    "./islands/Chat.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/KVDemo.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
